SELogger/config/routes.rb
Rails.application.routes.draw do
	root :to => 'events#index'
	resources :events do
  	resources :operators
	end
	get '/events/:id/public', to: 'events#public'
	get "/events/:event_id/operators/:id/logger", :to => "operators#log"
  # resources :operators
  # resources :events
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'
end

SELogger/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

SELogger/app/models/contact.rb
class Contact < ApplicationRecord
	after_create_commit { ContactBroadcastJob.perform_later self }
end

SELogger/app/models/event.rb
class Event < ApplicationRecord
end

SELogger/app/models/operator.rb
class Operator < ApplicationRecord
  belongs_to :event
end

SELogger/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

SELogger/app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  def public
    @event = Event.find( params[:id] )
    @qrz = QRZCallbook.new({ 'callsign' => 'w4h', 'username' => 'wa0pac', 'password' => 'needs490' })
    @listing = @qrz.get_listing
  end
  # GET /events/1
  # GET /events/1.json
  def show
    @operators = Operator.where(:event_id => params[:id] )
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:call_sign, :name, :location)
    end
end

SELogger/app/controllers/operators_controller.rb
class OperatorsController < ApplicationController
  before_action :set_operator, only: [:show, :edit, :update, :destroy]

  # GET /operators
  # GET /operators.json
  def index
    @operators = Operator.where(:event_id => params[:event_id] )
    @event = Event.all
  end

  # GET /operators/1
  # GET /operators/1.json
  def show
    @event = Event.find(params[:event_id])
  end

  def log
    @contact = Contact.all
  end
  # GET /operators/new
  def new
    @operator = Operator.new
  end

  # GET /operators/1/edit
  def edit
  end

  # POST /operators
  # POST /operators.json
  def create
    @operator = Operator.new(operator_params)

    respond_to do |format|
      if @operator.save
        format.html { redirect_to event_operator_url(:id => @operator.id), notice: 'Operator was successfully created.' }
        format.json { render :show, status: :created, location: @operator }
      else
        format.html { render :new }
        format.json { render json: @operator.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /operators/1
  # PATCH/PUT /operators/1.json
  def update
    respond_to do |format|
      if @operator.update(operator_params)
        format.html { redirect_to event_operator_url(:id => @operator.id), notice: 'Operator was successfully updated.' }
        format.json { render :show, status: :ok, location: @operator }
      else
        format.html { render :edit }
        format.json { render json: @operator.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /operators/1
  # DELETE /operators/1.json
  def destroy
    @operator.destroy
    respond_to do |format|
      format.html { redirect_to event_operators_url, notice: 'Operator was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_operator
      @operator = Operator.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def operator_params
      params.require(:operator).permit(:name, :call_sign, :location, :event_id)
    end
end

SELogger/app/helpers/application_helper.rb
module ApplicationHelper
end

SELogger/app/helpers/events_helper.rb
module EventsHelper
end

SELogger/app/helpers/operators_helper.rb
module OperatorsHelper
end

SELogger/app/views/contacts/_contact.html.erb
<div class="contact">

	<table>
  <thead>
    <tr>
      <th>band</th>
      <th>Call sign</th>
      <th>Location</th>
      <th>mode</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contact.each do |contact| %>
      <tr>
        <td><%= contact.band %></td>
        <td><%= contact.call_sign %></td>
        <td><%= contact.location %></td>
        <td><%= contact.mode %></td>
      </tr>
    <% end %>
  </tbody>
</table>

SELogger/app/views/events/_form.html.erb
<%= form_for(event) do |f| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :call_sign %>
    <%= f.text_field :call_sign %>
  </div>
  <div class="field">
    <%= f.label :location %>
    <%= f.text_field :location %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

SELogger/app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

SELogger/app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Events</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Call sign</th>
      <th>Location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.name %></td>
        <td><%= event.call_sign %></td>
        <td><%= event.location %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

SELogger/app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

SELogger/app/views/events/public.html.erb
<h1>Event: <%= @event.name.capitalize %></h1>
<h2>Location: <%= @event.location.capitalize %></h2>
<h2>Event Call Sign: <%= @event.call_sign.upcase %></h2>
<h3><%= @listing %></h3>

<script src="//maps.google.com/maps/api/js?v=3.18&sensor=false&client=&key=&libraries=geometry&language=&hl=&region="></script> 
<script src="//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/infobox/1.1.9/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->

<script type="text/javascript">
var handler = Gmaps.build('Google');
handler.buildMap({ internal: {id: 'multi_markers'}}, function(){
  var markers = handler.addMarkers([
    { lat: 43, lng: 3.5},
    { lat: 45, lng: 4},
    { lat: 47, lng: 3.5},
    { lat: 49, lng: 4},
    { lat: 51, lng: 3.5}
  ]);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
});
</script>
<div style='width: 800px;'>
  <div id="multi_markers" style='width: 800px; height: 400px;'></div>
</div>
    

SELogger/app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<div>
<h1>Event</h1>
<p>
  <strong>Name:</strong>
  <%= @event.name %><br>
  <strong>Call sign:</strong>
  <%= @event.call_sign %><br>
  <strong>Location:</strong>
  <%= @event.location %>
</p>
<%= link_to 'Public Page', :controller => "events", :action => "public" %><br>
<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

<h2>Operators</h2>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Call sign</th>
      <th>Location</th>
      <th>Event</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @operators.each do |operator| %>
      <tr>
        <td><%= operator.name %></td>
        <td><%= operator.call_sign %></td>
        <td><%= operator.location %></td>
        <td><%= @event.call_sign %></td>
        <td><%= link_to 'Show', event_operator_path(:id => operator.id, :event_id => params[:id]) %></td>
        <td><%= link_to 'Edit', edit_event_operator_path(:id => operator.id, :event_id => params[:id]) %></td>
        <td><%= link_to 'Destroy', event_operator_path(:id => operator.id, :event_id => params[:id]), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<%= link_to 'New Operator', new_event_operator_path(:event_id => params[:id]) %>
</div>

SELogger/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SELogger</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

SELogger/app/views/operators/_edit_form.html.erb
<%= form_for @operator, :url => {:action => :update, :controller => :operators} do |f| %>
  <% if operator.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(operator.errors.count, "error") %> prohibited this operator from being saved:</h2>

      <ul>
      <% operator.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :call_sign %>
    <%= f.text_field :call_sign %>
  </div>

  <div class="field">
    <%= f.label :location %>
    <%= f.text_field :location %>
  </div>

  <div class="field">
    <%= f.label :event_id %>
    <%= f.hidden_field :event_id, value: params[:event_id] %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

SELogger/app/views/operators/_new_form.html.erb
<%= form_for Operator.new, :url => {:action => :create, :controller => :operators} do |f| %>
  <% if operator.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(operator.errors.count, "error") %> prohibited this operator from being saved:</h2>

      <ul>
      <% operator.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :call_sign %>
    <%= f.text_field :call_sign %>
  </div>

  <div class="field">
    <%= f.label :location %>
    <%= f.text_field :location %>
  </div>

  <div class="field">
    <%= f.label :event_id %>
    <%= f.hidden_field :event_id, value: params[:event_id] %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

SELogger/app/views/operators/edit.html.erb
<h1>Editing Operator</h1>

<%= render 'edit_form', operator: @operator %>

<%= link_to 'Show', event_operator_path(@operator) %> |
<%= link_to 'Back', event_operators_path %>

SELogger/app/views/operators/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Operators</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Call sign</th>
      <th>Location</th>
      <th>Event</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @operators.each do |operator| %>
      <tr>
        <td><%= operator.name %></td>
        <td><%= operator.call_sign %></td>
        <td><%= operator.location %></td>
        <td><%= @event %></td>
        <td><%= link_to 'Show', event_operator_path(:id => operator.id) %></td>
        <td><%= link_to 'Edit', edit_event_operator_path(:id => operator.id) %></td>
        <td><%= link_to 'Destroy', event_operator_path(:id => operator.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<%= link_to 'New Operator', new_event_operator_path %>

SELogger/app/views/operators/log.html.erb
<h1>logger</h1>

<div class="contacts">
	<%= render partial: 'contacts/contact', locals: { contact: @contact } %>

	<form>
		<label>Call Sign:</label><br>
		<input type="text" name="call_sign" data-behavior="contact_speaker">
		<label>Name:</label><br>
		<input type="text" name="name" data-behavior="contact_speaker">
	</form>
</div>

SELogger/app/views/operators/new.html.erb
<h1>New Operator</h1>

<%= render 'new_form', operator: @operator %>

<%= link_to 'Back', event_operators_path %>

SELogger/app/views/operators/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @operator.name %>
</p>

<p>
  <strong>Call sign:</strong>
  <%= @operator.call_sign %>
</p>

<p>
  <strong>Location:</strong>
  <%= @operator.location %>
</p>

<p>
  <strong>Event:</strong>
  <%= @event.call_sign %>
</p>

<%= link_to 'Logger', :controller => 'operators', :action => 'log' %><br>
<%= link_to 'Edit', edit_event_operator_path(@operator) %> |
<%= link_to 'Back', event_path(:id => params[:event_id]) %>